version: '3.7'
services:
  seal_server:
    build:
      context: ./ServerImage
      dockerfile: Dockerfile
    volumes:
      - ../server:/server
    working_dir: /server

  gdbserver:
    build:
      context: ./DebugImage
      dockerfile: Dockerfile
    security_opt:
      - seccomp:unconfined
    ports:
      - "7776:22"
      - "7777:7777"
    volumes:
      - ../:/home/debugger/code
    working_dir: /home/debugger/code
    hostname: debug
