version: '3.7'
services:
  seal_server:
    build: ""
    volumes:
    - ./server:/server

  gdbserver:
    build:
      context: ".."
      dockerfile: DebugImage/Dockerfile
    image: clion_dev
    security_opt:
      - seccomp:unconfined
    container_name: debug
    ports:
      - "7776:22"
      - "7777:7777"
    volumes:
      - .:/home/debugger/code
    working_dir: /home/debugger/code
    hostname: debug
